import type { ProjectConfig } from '/#/config';
import { MenuTypeEnum, MenuModeEnum, TriggerEnum, MixSidebarTriggerEnum } from '/@/enums/menuEnum';
import { CacheTypeEnum } from '/@/enums/cacheEnum';
import {
  ContentEnum,
  PermissionModeEnum,
  ThemeEnum,
  RouterTransitionEnum,
  SettingButtonPositionEnum,
  SessionTimeoutProcessingEnum,
  TabsThemeEnum,
} from '/@/enums/appEnum';
import { SIDE_BAR_BG_COLOR_LIST, HEADER_PRESET_BG_COLOR_LIST } from './designSetting';
import { primaryColor } from '../../build/config/themeConfig';
import { darkMode } from '/@/settings/designSetting';

// ! You need to clear your browser cache after making changes
const setting: ProjectConfig = {
  // Whether to displaySettingButton
  showSettingButton: true,

  // Whether to displaytheme切换按钮
  showDarkModeToggle: true,

  // Set button position Optional
  // SettingButtonPositionEnum.AUTO: automatic selection
  // SettingButtonPositionEnum.HEADER: located in head
  // SettingButtonPositionEnum.FIXED: Fixed on the right
  settingButtonPosition: SettingButtonPositionEnum.AUTO,

  // permission mode,default前端角色permission mode
  // ROUTE_MAPPING: Front-end mode（The menu is generated by routing，default）
  // ROLE：Front-end mode（menu routing separate）
  // BACK：background mode
  permissionMode: PermissionModeEnum.BACK,

  // Permission cache storage location。default存放于localStorage
  permissionCacheType: CacheTypeEnum.LOCAL,

  // Session timeout handling solution
  // SessionTimeoutProcessingEnum.ROUTE_JUMP: Route to the login page
  // SessionTimeoutProcessingEnum.PAGE_COVERAGE: Generate login pop-up window，Overwrite current page
  sessionTimeoutProcessing: SessionTimeoutProcessingEnum.ROUTE_JUMP,

  // Project theme color
  themeColor: primaryColor,
  // update-begin--author:liaozhiyang---date:20250414--for：【QQYUN-11956】repairprojectSettingThe theme mode configured in Medium does not take effect
  // Project theme mode
  themeMode: darkMode,
  // update-end--author:liaozhiyang---date:20250414--for：【QQYUN-11956】repairprojectSettingThe theme mode configured in Medium does not take effect

  // Website gray mode，Dates open for possible tributes
  grayMode: false,

  // Color Weakness Mode
  colorWeak: false,

  // Whether to cancel the menu,top,Display multiple tabs, For use that may be embedded in other systems
  fullContent: false,

  // Topic content width
  contentMode: ContentEnum.FULL,

  // Whether to displaylogo
  showLogo: true,

  // Whether to display底部信息 copyright
  showFooter: false,

  // aiIcon display
  aiIconShow: false,

  // Head configuration
  headerSetting: {
    // background color
    bgColor: HEADER_PRESET_BG_COLOR_LIST[4],
    // fixed head
    fixed: true,
    // Whether to displaytop
    show: true,
    // theme
    theme: ThemeEnum.LIGHT,
    // Turn on lock screen function
    useLockPage: false,
    // Show full screen button
    showFullScreen: false,
    // Show official website button
    showDoc: false,
    // Show message center button
    showNotice: true,
    // Show menu search button
    showSearch: true,
  },

  // Menu configuration
  menuSetting: {
    // background color
    bgColor: SIDE_BAR_BG_COLOR_LIST[0],
    // Whether to pin the left menu
    fixed: true,
    // Menu collapse
    collapsed: false,
    // 折叠菜单时候Whether to display菜单名
    collapsedShowTitle: false,
    // Whether it can be dragged
    // Only limited to the opening of the left menu, the mouse has a drag bar on the right side of the menu
    canDrag: false,
    // Whether to show no dom
    show: true,
    // Whether to show dom
    hidden: false,
    // menu width
    menuWidth: 210,
    // Menu mode
    mode: MenuModeEnum.INLINE,
    // Menu type
    type: MenuTypeEnum.SIDEBAR,
    // 菜单theme
    theme: ThemeEnum.DARK,
    // update-begin--author:liaozhiyang---date:20241203---for：【issues/7522】solvemenuSetting tswarn
    // Adjust the text color of the left navigation bar to distinguish between color and dark (Does not correspond to configuration)
    isThemeBright: false,
    // update-end--author:liaozhiyang---date:20241203---for：【issues/7522】solvemenuSetting tswarn
    // split menu
    split: false,
    // top菜单布局
    topMenuAlign: 'center',
    // Collapse trigger position
    trigger: TriggerEnum.HEADER,
    // accordion mode，Show only one menu
    accordion: true,
    // Close the left hybrid menu to expand the menu when switching routes
    closeMixSidebarOnChange: false,
    // Mixed menu module on the left switches trigger mode ‘click’ |'hover'
    mixSideTrigger: MixSidebarTriggerEnum.CLICK,
    // Whether to pin the left mix menu
    mixSideFixed: false,
  },

  // multiple tags
  multiTabsSetting: {
    // Whether to keep open tabs after refreshing
    cache: false,
    // turn on
    show: true,
    // Is it possible to drag and drop
    canDrag: true,
    // turn on快速操作
    showQuick: true,
    // Whether to display刷新按钮
    showRedo: true,
    // Whether to display折叠按钮
    showFold: true,
    // Tab style
    theme: TabsThemeEnum.CARD,
  },

  // Animation configuration
  transitionSetting: {
    //  是否turn on切换动画
    // The disabled state will also disable pageLoading
    enable: true,

    // Animation name Route basic switching animation
    basicTransition: RouterTransitionEnum.FADE_SIDE,

    // Whether to turn on page switchingloading
    // Only open when enable=true
    openPageLoading: true,

    //Whether to turn on page switchingtop进度条
    openNProgress: true,
  },

  // 是否turn onKeepAlivecache  It is best to turn it off during development,不然每次都需要清除cache
  openKeepAlive: true,

  // Automatic lock screen time，for0No lock screen。 Unit minute default1hours
  lockTime: 0,

  // Show breadcrumbs
  showBreadCrumb: false,

  // Show breadcrumbs图标
  showBreadCrumbIcon: true,

  // Whether to use global error trapping
  useErrorHandle: false,

  // 是否turn on回到top
  useOpenBackTop: true,

  // Is it possible to embediframepage
  canEmbedIFramePage: true,

  // Whether to delete unclosed ones when switching interfacesmessageandnotify
  closeMessageOnSwitch: true,

  // Whether to cancel the sent but unresponsive messages when switching interfaces?httpask。
  // 如果turn on,Want to cover individual interfaces。Can be set on a separate interface
  removeAllHttpPending: false,
};

export default setting;
