#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import sys

# Dictionary for translating Chinese comments to English
translation_dict = {
    '创建人': 'Created by',
    '创建日期': 'Create date',
    '更新人': 'Updated by',
    '更新日期': 'Update date',
    '所属部门': 'Department',
    '应用名称': 'Application name',
    '应用描述': 'Application description',
    '应用类型': 'Application type',
    '应用图标': 'Application icon',
    '状态': 'Status',
    '名称': 'Name',
    '描述': 'Description',
    '类型': 'Type',
    '知识库名称': 'Knowledge base name',
    '字典名称': 'Dictionary name',
    '字典编码': 'Dictionary code',
    '字典类型0为string,1为number': 'Dictionary type: 0 for string, 1 for number',
    '字典id': 'Dictionary ID',
    '字典项文本': 'Dictionary item text',
    '字典项值': 'Dictionary item value',
    '用户名': 'Username',
    '物理字段名（文件数据集使用，存的是excel的字段标题）': 'Physical field name (used for file dataset, stores Excel field title)',
    '字典编码支持从表中取数据': 'Dictionary code supports getting data from table',
    '字典': 'Dictionary',
    '接收通知的邮件': 'Email for receiving notifications',
    '文件同步路径': 'File sync path',
    '积木报表预览权限表': 'JimuReport preview permission table',
    '角色id': 'Role ID',
    '权限id': 'Permission ID',
    '1字段 2按钮 3数据权限': '1 for field, 2 for button, 3 for data permission',
    '授权方式role角色，depart部门，user人': 'Authorization method: role for role, depart for department, user for person',
    '字典code': 'Dictionary code',
    '字典表': 'Dictionary table',
    '字典Text': 'Dictionary Text',
    '查询配置字典text': 'Query configuration dictionary text',
    '查询配置字典code': 'Query configuration dictionary code',
    '历史消息数': 'Historical message count',
    '所属部门编码': 'Department code',
    '状态（enable=启用、disable=禁用、release=发布）': 'Status (enable=enabled, disable=disabled, release=published)',
    '租户id': 'Tenant ID',
    '开场白': 'Opening remarks',
    '提示词': 'Prompt',
    '模型id': 'Model ID',
    '知识库': 'Knowledge base',
    '流程': 'Flow',
    '元数据': 'Metadata',
    '预设问题': 'Preset questions',
    '快捷指令': 'Quick command',
    # Additional common Chinese terms
    '用户': 'User',
    '角色': 'Role',
    '菜单': 'Menu',
    '权限': 'Permission',
    '部门': 'Department',
    '岗位': 'Position',
    '日志': 'Log',
    '消息': 'Message',
    '通知': 'Notice',
    '文件': 'File',
    '主键': 'Primary key',
    '编码': 'Code',
    '时间': 'Time',
    '日期': 'Date',
    '标题': 'Title',
    '内容': 'Content',
    '地址': 'Address',
    '电话': 'Phone',
    '邮箱': 'Email',
    '密码': 'Password',
    '确认密码': 'Confirm password',
    '启用': 'Enable',
    '禁用': 'Disable',
    '删除': 'Delete',
    '修改': 'Modify',
    '添加': 'Add',
    '查询': 'Query',
    '搜索': 'Search',
    '重置': 'Reset',
    '提交': 'Submit',
    '取消': 'Cancel',
    '保存': 'Save',
    '返回': 'Return',
    '下一步': 'Next',
    '上一步': 'Previous',
    '完成': 'Complete',
    '开始': 'Start',
    '结束': 'End',
    '首页': 'Home',
    '帮助': 'Help',
    '关于': 'About',
    '设置': 'Settings',
    '退出': 'Exit',
    '登录': 'Login',
    '注册': 'Register',
    '忘记密码': 'Forgot password',
    '记住我': 'Remember me',
    '验证码': 'Verification code',
    '用户名': 'Username',
    '账号': 'Account',
    '密码': 'Password',
    '确认密码': 'Confirm password',
    '手机号': 'Mobile phone',
    '邮箱': 'Email',
    '性别': 'Gender',
    '男': 'Male',
    '女': 'Female',
    '生日': 'Birthday',
    '年龄': 'Age',
    '身份证': 'ID card',
    '地址': 'Address',
    '邮编': 'Postal code',
    '个人简介': 'Personal profile',
    '头像': 'Avatar',
    '昵称': 'Nickname',
    '真实姓名': 'Real name',
    '公司': 'Company',
    '职位': 'Position',
    '部门': 'Department',
    '工号': 'Employee ID',
    '入职时间': 'Entry date',
    '离职时间': 'Resignation date',
    '在职': 'Active',
    '离职': 'Resigned',
    '请假': 'Leave',
    '加班': 'Overtime',
    '考勤': 'Attendance',
    '薪资': 'Salary',
    '银行账号': 'Bank account',
    '开户行': 'Bank name',
    '银行卡号': 'Bank card number',
    '产品': 'Product',
    '产品名称': 'Product name',
    '产品编码': 'Product code',
    '产品类型': 'Product type',
    '产品价格': 'Product price',
    '产品描述': 'Product description',
    '产品图片': 'Product image',
    '库存': 'Inventory',
    '库存数量': 'Inventory quantity',
    '库存预警': 'Inventory warning',
    '入库': 'Stock in',
    '出库': 'Stock out',
    '盘点': 'Inventory check',
    '调拨': 'Transfer',
    '报废': 'Scrap',
    '供应商': 'Supplier',
    '供应商名称': 'Supplier name',
    '供应商编码': 'Supplier code',
    '供应商联系人': 'Supplier contact',
    '供应商电话': 'Supplier phone',
    '供应商地址': 'Supplier address',
    '采购': 'Purchase',
    '采购单': 'Purchase order',
    '采购日期': 'Purchase date',
    '采购金额': 'Purchase amount',
    '采购人': 'Purchaser',
    '审批人': 'Approver',
    '审批状态': 'Approval status',
    '审批时间': 'Approval time',
    '审批意见': 'Approval comments',
    '客户': 'Customer',
    '客户名称': 'Customer name',
    '客户编码': 'Customer code',
    '客户联系人': 'Customer contact',
    '客户电话': 'Customer phone',
    '客户地址': 'Customer address',
    '销售': 'Sales',
    '销售单': 'Sales order',
    '销售日期': 'Sales date',
    '销售金额': 'Sales amount',
    '销售人': 'Salesperson',
    '合同': 'Contract',
    '合同编号': 'Contract number',
    '合同名称': 'Contract name',
    '合同类型': 'Contract type',
    '合同金额': 'Contract amount',
    '签订日期': 'Signing date',
    '生效日期': 'Effective date',
    '到期日期': 'Expiry date',
    '合同状态': 'Contract status',
    '项目': 'Project',
    '项目名称': 'Project name',
    '项目编码': 'Project code',
    '项目类型': 'Project type',
    '项目经理': 'Project manager',
    '项目成员': 'Project member',
    '开始时间': 'Start time',
    '结束时间': 'End time',
    '项目状态': 'Project status',
    '任务': 'Task',
    '任务名称': 'Task name',
    '任务描述': 'Task description',
    '任务状态': 'Task status',
    '优先级': 'Priority',
    '截止时间': 'Deadline',
    '分配人': 'Assigner',
    '执行人': 'Executor',
    '工时': 'Working hours',
    '报销': 'Reimbursement',
    '报销单': 'Reimbursement form',
    '报销金额': 'Reimbursement amount',
    '报销人': 'Reimbursement applicant',
    '报销类型': 'Reimbursement type',
    '报销日期': 'Reimbursement date',
    '发票': 'Invoice',
    '发票号码': 'Invoice number',
    '发票金额': 'Invoice amount',
    '发票类型': 'Invoice type',
    '开票日期': 'Invoice date',
    '发票状态': 'Invoice status',
    '财务': 'Finance',
    '会计期间': 'Accounting period',
    '会计科目': 'Accounting subject',
    '借方金额': 'Debit amount',
    '贷方金额': 'Credit amount',
    '余额': 'Balance',
    '期初余额': 'Opening balance',
    '期末余额': 'Closing balance',
    '凭证号': 'Voucher number',
    '凭证日期': 'Voucher date',
    '凭证类型': 'Voucher type',
    '制单人': 'Creator',
    '审核人': 'Auditor',
    '审核状态': 'Audit status',
    '审核时间': 'Audit time',
    '备注': 'Remarks',
    '附件': 'Attachment',
    '图片': 'Image',
    '文档': 'Document',
    '视频': 'Video',
    '音频': 'Audio',
    '压缩包': 'Compressed package',
    '上传时间': 'Upload time',
    '上传人': 'Uploader',
    '文件大小': 'File size',
    '文件类型': 'File type',
    '下载次数': 'Download count',
    '最后下载时间': 'Last download time',
    '系统': 'System',
    '系统名称': 'System name',
    '系统版本': 'System version',
    '系统配置': 'System configuration',
    '参数名称': 'Parameter name',
    '参数值': 'Parameter value',
    '参数描述': 'Parameter description',
    '操作日志': 'Operation log',
    '操作人': 'Operator',
    '操作时间': 'Operation time',
    '操作类型': 'Operation type',
    '操作内容': 'Operation content',
    '操作结果': 'Operation result',
    '登录日志': 'Login log',
    '登录时间': 'Login time',
    '登录IP': 'Login IP',
    '登录地点': 'Login location',
    '浏览器': 'Browser',
    '操作系统': 'Operating system',
    '会话': 'Session',
    '会话ID': 'Session ID',
    '会话创建时间': 'Session creation time',
    '会话过期时间': 'Session expiry time',
    '缓存': 'Cache',
    '缓存键': 'Cache key',
    '缓存值': 'Cache value',
    '缓存过期时间': 'Cache expiry time',
    '队列': 'Queue',
    '队列名称': 'Queue name',
    '队列消息': 'Queue message',
    '消息状态': 'Message status',
    '发送时间': 'Send time',
    '接收时间': 'Receive time',
    '处理时间': 'Process time',
    '重试次数': 'Retry count',
    '定时任务': 'Scheduled task',
    '任务名称': 'Task name',
    '任务组': 'Task group',
    '任务类': 'Task class',
    '执行时间': 'Execution time',
    '执行状态': 'Execution status',
    '下次执行时间': 'Next execution time',
    '执行间隔': 'Execution interval',
    '监控': 'Monitor',
    '监控项': 'Monitor item',
    '监控值': 'Monitor value',
    '阈值': 'Threshold',
    '报警': 'Alarm',
    '报警级别': 'Alarm level',
    '报警内容': 'Alarm content',
    '报警时间': 'Alarm time',
    '处理状态': 'Process status',
    '备份': 'Backup',
    '备份名称': 'Backup name',
    '备份类型': 'Backup type',
    '备份大小': 'Backup size',
    '备份时间': 'Backup time',
    '恢复': 'Restore',
    '恢复名称': 'Restore name',
    '恢复时间': 'Restore time',
    '恢复状态': 'Restore status',
    '版本': 'Version',
    '版本号': 'Version number',
    '版本名称': 'Version name',
    '版本描述': 'Version description',
    '发布时间': 'Release time',
    '发布人': 'Publisher',
    '下载地址': 'Download URL',
    '更新日志': 'Update log',
    '更新内容': 'Update content',
    '更新时间': 'Update time',
    '更新人': 'Updater',
    '权限管理': 'Permission management',
    '角色管理': 'Role management',
    '用户管理': 'User management',
    '菜单管理': 'Menu management',
    '字典管理': 'Dictionary management',
    '部门管理': 'Department management',
    '岗位管理': 'Position management',
    '日志管理': 'Log management',
    '系统设置': 'System settings',
    '数据字典': 'Data dictionary',
    '业务字典': 'Business dictionary',
    '系统字典': 'System dictionary',
    '字典项': 'Dictionary item',
    '字典类型': 'Dictionary type',
    '字典值': 'Dictionary value',
    '字典文本': 'Dictionary text',
    '字典编码': 'Dictionary code',
    '字典名称': 'Dictionary name',
    '字典描述': 'Dictionary description',
    '字典状态': 'Dictionary status',
    '字典排序': 'Dictionary order',
    '字典备注': 'Dictionary remarks',
    '父级ID': 'Parent ID',
    '子级ID': 'Child ID',
    '层级': 'Level',
    '路径': 'Path',
    '排序': 'Order',
    '图标': 'Icon',
    '路由': 'Route',
    '组件': 'Component',
    '权限标识': 'Permission identifier',
    '权限名称': 'Permission name',
    '权限描述': 'Permission description',
    '权限类型': 'Permission type',
    '权限状态': 'Permission status',
    '角色标识': 'Role identifier',
    '角色名称': 'Role name',
    '角色描述': 'Role description',
    '角色类型': 'Role type',
    '角色状态': 'Role status',
    '用户标识': 'User identifier',
    '用户名称': 'User name',
    '用户描述': 'User description',
    '用户类型': 'User type',
    '用户状态': 'User status',
    '部门标识': 'Department identifier',
    '部门名称': 'Department name',
    '部门描述': 'Department description',
    '部门类型': 'Department type',
    '部门状态': 'Department status',
    '岗位标识': 'Position identifier',
    '岗位名称': 'Position name',
    '岗位描述': 'Position description',
    '岗位类型': 'Position type',
    '岗位状态': 'Position status',
    '日志标识': 'Log identifier',
    '日志名称': 'Log name',
    '日志描述': 'Log description',
    '日志类型': 'Log type',
    '日志级别': 'Log level',
    '日志状态': 'Log status',
    '操作类型': 'Operation type',
    '操作模块': 'Operation module',
    '操作功能': 'Operation function',
    '操作描述': 'Operation description',
    '操作结果': 'Operation result',
    '操作IP': 'Operation IP',
    '操作地点': 'Operation location',
    '操作浏览器': 'Operation browser',
    '操作系统': 'Operating system',
    '请求方法': 'Request method',
    '请求URL': 'Request URL',
    '请求参数': 'Request parameters',
    '响应结果': 'Response result',
    '响应时间': 'Response time',
    '响应状态': 'Response status',
    '异常信息': 'Exception information',
    '堆栈信息': 'Stack trace information',
    # Additional terms found in the file
    '积木报表预览权限表': 'JimuReport preview permission table',
    '查询配置字典table': 'Query configuration dictionary table',
    '字典CODE': 'Dictionary CODE',
    '字典Code': 'Dictionary Code',
    '关联系统用户名': 'Associated system username',
    '权限表': 'Permission table',
    '文件名称': 'File name',
    '文件地址': 'File address',
    '消息类型1:通知公告2:系统消息': 'Message type 1: Notice announcement 2: System message',
    '通告对象类型（USER:指定用户，ALL:全体用户）': 'Announcement target type (USER: Specified user, ALL: All users)',
    # Additional terms found in the file
    '来源类型( report 积木报表 screen 大屏  drag 仪表盘)': 'Source type (report JimuReport screen large screen drag dashboard)',
    '积木报表导出计划表': 'JimuReport export plan table',
    '积木报表自动导出记录表': 'JimuReport auto export record table',
    '积木图库表': 'JimuReport chart library table',
    '积木设计器id': 'JimuReport designer ID',
    '是否启用查询配置1是0否': 'Whether to enable query configuration 1 yes 0 no',
    '部门权限表': 'Department permission table',
    '部门角色权限表': 'Department role permission table',
}

def translate_comments_in_file(file_path):
    """Translate Chinese comments in SQL file to English"""
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
        
        # Create a new file with translated comments
        new_content = content
        for chinese, english in translation_dict.items():
            # Replace Chinese comments with English
            pattern = r"COMMENT\s+'" + re.escape(chinese) + r"'"
            replacement = f"COMMENT '{english}'"
            new_content = re.sub(pattern, replacement, new_content)
            
            # Also handle cases without quotes
            pattern = r"COMMENT\s+" + re.escape(chinese)
            replacement = f"COMMENT {english}"
            new_content = re.sub(pattern, replacement, new_content)
        
        # Write the translated content to a new file
        new_file_path = file_path.replace('.sql', '_translated.sql')
        with open(new_file_path, 'w', encoding='utf-8') as file:
            file.write(new_content)
        
        print(f"Translation completed. Output saved to: {new_file_path}")
        return new_file_path
        
    except Exception as e:
        print(f"Error processing file: {e}")
        return None

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python translate_sql_comments.py <sql_file_path>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    translate_comments_in_file(file_path)