#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script to translate Chinese text to English in jeecgboot-mysql-5.7_complete.sql file
and check for duplicate translations
"""

import re

def translate_and_check_duplicates():
    """
    Translate Chinese text to English and check for duplicates
    """
    # Comprehensive Chinese to English translations
    translations = {
        # Basic terms
        "创建人": "Created by",
        "创建日期": "Create date",
        "更新人": "Updated by", 
        "更新日期": "Update date",
        "所属部门": "Department",
        "所属公司": "Company",
        "性别": "Gender",
        "生日": "Birthday",
        "头像": "Avatar",
        "状态": "Status",
        "邮箱": "Email",
        "手机号": "Phone",
        "工号": "Employee ID",
        "职位": "Position",
        "职级": "Job Level",
        "入职时间": "Join Date",
        "离职时间": "Leave Date",
        "是否离职": "Is Resigned",
        "离职原因": "Resignation Reason",
        "离职类型": "Resignation Type",
        "离职交接人": "Resignation Handover",
        "离职交接时间": "Handover Time",
        "离职备注": "Resignation Remarks",
        "离职状态": "Resignation Status",
        "离职申请时间": "Resignation Application Time",
        "离职审批时间": "Resignation Approval Time",
        "离职生效时间": "Resignation Effective Time",
        "离职申请人": "Resignation Applicant",
        "离职审批人": "Resignation Approver",
        "离职生效人": "Resignation Effective Person",
        "离职审批时间": "",
        
        # System terms
        "用户": "User",
        "角色": "Role",
        "菜单": "Menu",
        "权限": "Permission",
        "部门": "Department",
        "字典": "Dictionary",
        "日志": "Log",
        "通知": "Notice",
        "消息": "Message",
        "系统": "System",
        "设置": "Settings",
        "管理": "Management",
        "查询": "Query",
        "添加": "Add",
        "编辑": "Edit",
        "删除": "Delete",
        "保存": "Save",
        "取消": "Cancel",
        "确定": "Confirm",
        "提交": "Submit",
        "重置": "Reset",
        "搜索": "Search",
        "导出": "Export",
        "导入": "Import",
        "打印": "Print",
        "预览": "Preview",
        "详情": "Details",
        "列表": "List",
        "表单": "Form",
        "表格": "Table",
        "图表": "Chart",
        "报表": "Report",
        "数据": "Data",
        "信息": "Information",
        "状态": "Status",
        "类型": "Type",
        "名称": "Name",
        "描述": "Description",
        "内容": "Content",
        "标题": "Title",
        "时间": "Time",
        "日期": "Date",
        "开始": "Start",
        "结束": "End",
        "创建": "Create",
        "更新": "Update",
        "启用": "Enable",
        "禁用": "Disable",
        "是": "Yes",
        "否": "No",
        "男": "Male",
        "女": "Female",
        "未知": "Unknown",
        "其他": "Other",
        "全部": "All",
        "部分": "Partial",
        "选择": "Select",
        "完成": "Complete",
        "进行中": "In Progress",
        "待处理": "Pending",
        "已处理": "Processed",
        "已取消": "Cancelled",
        "已关闭": "Closed",
        "已归档": "Archived",
        "草稿": "Draft",
        "已发布": "Published",
        "已审核": "Audited",
        "未审核": "Unaudited",
        "已拒绝": "Rejected",
        "已通过": "Approved",
        "未批准": "Unapproved",
        "已确认": "Confirmed",
        "未确认": "Unconfirmed",
        "已发送": "Sent",
        "未发送": "Unsent",
        "已接收": "Received",
        "未接收": "Unreceived",
        "已读": "Read",
        "未读": "Unread",
        "已回复": "Replied",
        "未回复": "Unreplied",
        "已标记": "Marked",
        "未标记": "Unmarked",
        "已收藏": "Favorited",
        "未收藏": "Unfavorited",
        "已分享": "Shared",
        "未分享": "Unshared",
        "已下载": "Downloaded",
        "未下载": "Undownloaded",
        "已上传": "Uploaded",
        "未上传": "Unuploaded",
        "已同步": "Synchronized",
        "未同步": "Unsynchronized",
        "已备份": "Backed Up",
        "未备份": "Not Backed Up",
        "已恢复": "Restored",
        "未恢复": "Not Restored",
        "已锁定": "Locked",
        "未锁定": "Unlocked",
        "已激活": "Activated",
        "未激活": "Inactive",
        "已注册": "Registered",
        "未注册": "Unregistered",
        "已登录": "Logged In",
        "未登录": "Not Logged In",
        "已退出": "Logged Out",
        "已超时": "Timeout",
        "已过期": "Expired",
        "已失效": "Invalid",
        "已生效": "Effective",
        "已禁用": "Disabled",
        "已启用": "Enabled",
        "已隐藏": "Hidden",
        "已显示": "Visible",
        "已排序": "Sorted",
        "未排序": "Unsorted",
        "已分组": "Grouped",
        "未分组": "Ungrouped",
        "已筛选": "Filtered",
        "未筛选": "Unfiltered",
        "已搜索": "Searched",
        "未搜索": "Not Searched",
        "已刷新": "Refreshed",
        "未刷新": "Not Refreshed",
        "已加载": "Loaded",
        "未加载": "Not Loaded",
        "已保存": "Saved",
        "未保存": "Not Saved",
        "已提交": "Submitted",
        "未提交": "Not Submitted",
        "已取消": "Cancelled",
        "未取消": "Not Cancelled",
        "已完成": "Completed",
        "未完成": "Incomplete",
        "已开始": "Started",
        "未开始": "Not Started",
        "已暂停": "Paused",
        "未暂停": "Not Paused",
        "已继续": "Resumed",
        "未继续": "Not Resumed",
        "已停止": "Stopped",
        "未停止": "Not Stopped",
        "已重启": "Restarted",
        "未重启": "Not Restarted",
        "已安装": "Installed",
        "未安装": "Not Installed",
        "已卸载": "Uninstalled",
        "未卸载": "Not Uninstalled",
        "已更新": "Updated",
        "未更新": "Not Updated",
        "已升级": "Upgraded",
        "未升级": "Not Upgraded",
        "已降级": "Downgraded",
        "未降级": "Not Downgraded",
        "已修复": "Fixed",
        "未修复": "Not Fixed",
        "已测试": "Tested",
        "未测试": "Not Tested",
        "已部署": "Deployed",
        "未部署": "Not Deployed",
        "已发布": "Published",
        "未发布": "Not Published",
        "已归档": "Archived",
        "未归档": "Not Archived",
        "已删除": "Deleted",
        "未删除": "Not Deleted",
        "已恢复": "Restored",
        "未恢复": "Not Restored",
        "已备份": "Backed Up",
        "未备份": "Not Backed Up",
        "已还原": "Restored",
        "未还原": "Not Restored",
        "已复制": "Copied",
        "未复制": "Not Copied",
        "已移动": "Moved",
        "未移动": "Not Moved",
        "已重命名": "Renamed",
        "未重命名": "Not Renamed",
        "已修改": "Modified",
        "未修改": "Not Modified",
        "已查看": "Viewed",
        "未查看": "Not Viewed",
        "已编辑": "Edited",
        "未编辑": "Not Edited",
        "已创建": "Created",
        "未创建": "Not Created",
        "已生成": "Generated",
        "未生成": "Not Generated",
        "已计算": "Calculated",
        "未计算": "Not Calculated",
        "已统计": "Counted",
        "未统计": "Not Counted",
        "已分析": "Analyzed",
        "未分析": "Not Analyzed",
        "已预测": "Predicted",
        "未预测": "Not Predicted",
        "已推荐": "Recommended",
        "未推荐": "Not Recommended",
        "已评价": "Rated",
        "未评价": "Not Rated",
        "已评论": "Commented",
        "未评论": "Not Commented",
        "已点赞": "Liked",
        "未点赞": "Not Liked",
        "已收藏": "Favorited",
        "未收藏": "Not Favorited",
        "已关注": "Followed",
        "未关注": "Not Followed",
        "已分享": "Shared",
        "未分享": "Not Shared",
        "已转发": "Forwarded",
        "未转发": "Not Forwarded",
        "已举报": "Reported",
        "未举报": "Not Reported",
        "已屏蔽": "Blocked",
        "未屏蔽": "Not Blocked",
        "已拉黑": "Blacklisted",
        "未拉黑": "Not Blacklisted",
        "已解封": "Unblocked",
        "未解封": "Not Unblocked",
        "已认证": "Authenticated",
        "未认证": "Not Authenticated",
        "已验证": "Verified",
        "未验证": "Not Verified",
        "已授权": "Authorized",
        "未授权": "Not Authorized",
        "管理员": "Administrator",
        "超级管理员": "Super Administrator",
        "普通用户": "Regular User",
        "访客": "Guest",
        "操作": "Operation",
        "功能": "Function",
        "模块": "Module",
        "页面": "Page",
        "按钮": "Button",
        "链接": "Link",
        "图片": "Image",
        "文件": "File",
        "文档": "Document",
        "视频": "Video",
        "音频": "Audio",
        "配置": "Configuration",
        "参数": "Parameter",
        "选项": "Option",
        "值": "Value",
        "字段": "Field",
        "表": "Table",
        "视图": "View",
        "索引": "Index",
        "主键": "Primary Key",
        "外键": "Foreign Key",
        "约束": "Constraint",
        "触发器": "Trigger",
        "存储过程": "Stored Procedure",
        "函数": "Function",
        "包": "Package",
        "类": "Class",
        "对象": "Object",
        "属性": "Property",
        "方法": "Method",
        "接口": "Interface",
        "实现": "Implementation",
        "继承": "Inheritance",
        "封装": "Encapsulation",
        "多态": "Polymorphism",
        "抽象": "Abstract",
        "实例": "Instance",
        "引用": "Reference",
        "指针": "Pointer",
        "数组": "Array",
        "列表": "List",
        "集合": "Set",
        "映射": "Map",
        "队列": "Queue",
        "栈": "Stack",
        "树": "Tree",
        "图": "Graph",
        "算法": "Algorithm",
        "排序": "Sorting",
        "查找": "Search",
        "过滤": "Filter",
        "分组": "Group",
        "聚合": "Aggregate",
        "连接": "Join",
        "合并": "Merge",
        "拆分": "Split",
        "转换": "Convert",
        "格式化": "Format",
        "解析": "Parse",
        "序列化": "Serialize",
        "反序列化": "Deserialize",
        "编码": "Encode",
        "解码": "Decode",
        "加密": "Encrypt",
        "解密": "Decrypt",
        "压缩": "Compress",
        "解压": "Decompress",
        "备份": "Backup",
        "恢复": "Restore",
        "同步": "Synchronize",
        "异步": "Asynchronous",
        "并发": "Concurrent",
        "并行": "Parallel",
        "串行": "Serial",
        "事务": "Transaction",
        "提交": "Commit",
        "回滚": "Rollback",
        "锁": "Lock",
        "死锁": "Deadlock",
        "超时": "Timeout",
        "重试": "Retry",
        "缓存": "Cache",
        "会话": "Session",
        "令牌": "Token",
        "签名": "Signature",
        "证书": "Certificate",
        "授权": "Authorization",
        "认证": "Authentication",
        "权限": "Permission",
        "角色": "Role",
        "用户": "User",
        "组": "Group",
        "组织": "Organization",
        "公司": "Company",
        "部门": "Department",
        "职位": "Position",
        "员工": "Employee",
        "客户": "Customer",
        "供应商": "Supplier",
        "产品": "Product",
        "服务": "Service",
        "订单": "Order",
        "合同": "Contract",
        "发票": "Invoice",
        "收据": "Receipt",
        "付款": "Payment",
        "退款": "Refund",
        "折扣": "Discount",
        "优惠券": "Coupon",
        "促销": "Promotion",
        "活动": "Activity",
        "任务": "Task",
        "项目": "Project",
        "计划": "Plan",
        "进度": "Progress",
        "报告": "Report",
        "统计": "Statistics",
        "分析": "Analysis",
        "预测": "Forecast",
        "建议": "Suggestion",
        "推荐": "Recommendation",
        "评价": "Evaluation",
        "评论": "Comment",
        "反馈": "Feedback",
        "投诉": "Complaint",
        "帮助": "Help",
        "支持": "Support",
        "文档": "Documentation",
        "教程": "Tutorial",
        "指南": "Guide",
        "说明": "Instructions",
        "介绍": "Introduction",
        "概述": "Overview",
        "摘要": "Summary",
        "详情": "Details",
        "备注": "Remarks",
        "注意": "Note",
        "警告": "Warning",
        "错误": "Error",
        "异常": "Exception",
        "故障": "Failure",
        "问题": "Problem",
        "解决方案": "Solution",
        "修复": "Fix",
        "更新": "Update",
        "升级": "Upgrade",
        "版本": "Version",
        "发布": "Release",
        "补丁": "Patch",
        "测试": "Test",
        "调试": "Debug",
        "验证": "Verify",
        "检查": "Check",
        "审查": "Review",
        "审计": "Audit",
        "日志": "Log",
        "记录": "Record",
        "历史": "History",
        "跟踪": "Trace",
        "监控": "Monitor",
        "警报": "Alert",
        "通知": "Notification",
        "消息": "Message",
        "邮件": "Email",
        "短信": "SMS",
        "推送": "Push",
        "订阅": "Subscribe",
        "取消订阅": "Unsubscribe",
        "关注": "Follow",
        "取消关注": "Unfollow",
        "点赞": "Like",
        "取消点赞": "Unlike",
        "收藏": "Favorite",
        "取消收藏": "Unfavorite",
        "分享": "Share",
        "转发": "Forward",
        "举报": "Report",
        "屏蔽": "Block",
        "拉黑": "Blacklist",
        "解封": "Unblock",
        "注册": "Register",
        "登录": "Login",
        "退出": "Logout",
        "修改密码": "Change Password",
        "重置密码": "Reset Password",
        "找回密码": "Retrieve Password",
        "验证码": "Verification Code",
        "安全": "Security",
        "隐私": "Privacy",
        "条款": "Terms",
        "条件": "Conditions",
        "协议": "Agreement",
        "政策": "Policy",
        "规则": "Rules",
        "规范": "Standards",
        "标准": "Standard",
        "要求": "Requirements",
        "需求": "Requirements",
        "规格": "Specification",
        "设计": "Design",
        "开发": "Development",
        "部署": "Deployment",
        "维护": "Maintenance",
        "运营": "Operation",
        "优化": "Optimization",
        "改进": "Improvement",
        "增强": "Enhancement",
        "扩展": "Extension",
        "插件": "Plugin",
        "模块": "Module",
        "组件": "Component",
        "控件": "Control",
        "元素": "Element",
        "样式": "Style",
        "主题": "Theme",
        "模板": "Template",
        "布局": "Layout",
        "结构": "Structure",
        "框架": "Framework",
        "库": "Library",
        "包": "Package",
        "依赖": "Dependency",
        "配置": "Configuration",
        "环境": "Environment",
        "服务器": "Server",
        "客户端": "Client",
        "浏览器": "Browser",
        "设备": "Device",
        "平台": "Platform",
        "系统": "System",
        "软件": "Software",
        "应用": "Application",
        "程序": "Program",
        "代码": "Code",
        "脚本": "Script",
        "命令": "Command",
        "指令": "Instruction",
        "操作": "Operation",
        "执行": "Execute",
        "运行": "Run",
        "启动": "Start",
        "停止": "Stop",
        "暂停": "Pause",
        "继续": "Continue",
        "重启": "Restart",
        "关闭": "Close",
        "打开": "Open",
        "创建": "Create",
        "新建": "New",
        "编辑": "Edit",
        "修改": "Modify",
        "更新": "Update",
        "删除": "Delete",
        "移除": "Remove",
        "清空": "Clear",
        "重置": "Reset",
        "恢复": "Restore",
        "还原": "Restore",
        "备份": "Backup",
        "导入": "Import",
        "导出": "Export",
        "上传": "Upload",
        "下载": "Download",
        "同步": "Sync",
        "复制": "Copy",
        "粘贴": "Paste",
        "剪切": "Cut",
        "撤销": "Undo",
        "重做": "Redo",
        "查找": "Find",
        "替换": "Replace",
        "搜索": "Search",
        "过滤": "Filter",
        "排序": "Sort",
        "分组": "Group",
        "统计": "Statistics",
        "汇总": "Summary",
        "计算": "Calculate",
        "分析": "Analyze",
        "预测": "Predict",
        "推荐": "Recommend",
        "评价": "Rate",
        "评论": "Comment",
        "点赞": "Like",
        "收藏": "Favorite",
        "分享": "Share",
        "转发": "Forward",
        "举报": "Report",
        "关注": "Follow",
        "订阅": "Subscribe",
        "加入": "Join",
        "退出": "Leave",
        "登录": "Login",
        "注册": "Register",
        "退出": "Logout",
        "修改": "Modify",
        "更新": "Update",
        "保存": "Save",
        "提交": "Submit",
        "取消": "Cancel",
        "确认": "Confirm",
        "确定": "OK",
        "是": "Yes",
        "否": "No",
        "好的": "OK",
        "完成": "Complete",
        "成功": "Success",
        "失败": "Failure",
        "错误": "Error",
        "警告": "Warning",
        "信息": "Information",
        "提示": "Tip",
        "帮助": "Help",
        "关于": "About",
        "设置": "Settings",
        "选项": "Options",
        "偏好": "Preferences",
        "配置": "Configuration",
        "工具": "Tools",
        "扩展": "Extensions",
        "插件": "Plugins",
        "主题": "Themes",
        "语言": "Language",
        "地区": "Region",
        "时区": "Timezone",
        "货币": "Currency",
        "单位": "Unit",
        "格式": "Format",
        "样式": "Style",
        "颜色": "Color",
        "字体": "Font",
        "大小": "Size",
        "位置": "Position",
        "方向": "Direction",
        "对齐": "Alignment",
        "间距": "Spacing",
        "边距": "Margin",
        "填充": "Padding",
        "边框": "Border",
        "背景": "Background",
        "前景": "Foreground",
        "透明度": "Opacity",
        "可见性": "Visibility",
        "显示": "Show",
        "隐藏": "Hide",
        "展开": "Expand",
        "折叠": "Collapse",
        "最大化": "Maximize",
        "最小化": "Minimize",
        "全屏": "Fullscreen",
        "窗口": "Window",
        "标签页": "Tab",
        "菜单": "Menu",
        "工具栏": "Toolbar",
        "状态栏": "Status Bar",
        "导航栏": "Navigation Bar",
        "侧边栏": "Sidebar",
        "内容区": "Content Area",
        "页脚": "Footer",
        "页眉": "Header",
        "标题": "Title",
        "副标题": "Subtitle",
        "段落": "Paragraph",
        "文本": "Text",
        "链接": "Link",
        "按钮": "Button",
        "输入框": "Input Field",
        "下拉框": "Dropdown",
        "复选框": "Checkbox",
        "单选框": "Radio Button",
        "开关": "Switch",
        "滑块": "Slider",
        "进度条": "Progress Bar",
        "加载中": "Loading",
        "等待中": "Waiting",
        "处理中": "Processing",
        "已完成": "Completed",
        "已取消": "Cancelled",
        "已失败": "Failed",
        "已成功": "Succeeded",
        "进行中": "In Progress",
        "待处理": "Pending",
        "已处理": "Processed",
        "未处理": "Unprocessed",
        "已审核": "Reviewed",
        "未审核": "Unreviewed",
        "已批准": "Approved",
        "未批准": "Unapproved",
        "已拒绝": "Rejected",
        "未拒绝": "Not Rejected",
        "已发送": "Sent",
        "未发送": "Not Sent",
        "已接收": "Received",
        "未接收": "Not Received",
        "已读": "Read",
        "未读": "Unread",
        "已回复": "Replied",
        "未回复": "Not Replied",
        "已标记": "Marked",
        "未标记": "Unmarked",
        "已归档": "Archived",
        "未归档": "Not Archived",
        "已删除": "Deleted",
        "未删除": "Not Deleted",
        "已恢复": "Restored",
        "未恢复": "Not Restored",
        "已备份": "Backed Up",
        "未备份": "Not Backed Up",
        "已还原": "Restored",
        "未还原": "Not Restored",
        "已复制": "Copied",
        "未复制": "Not Copied",
        "已移动": "Moved",
        "未移动": "Not Moved",
        "已重命名": "Renamed",
        "未重命名": "Not Renamed",
        "已修改": "Modified",
        "未修改": "Not Modified",
        "已查看": "Viewed",
        "未查看": "Not Viewed",
        "已编辑": "Edited",
        "未编辑": "Not Edited",
        "已创建": "Created",
        "未创建": "Not Created",
        "已生成": "Generated",
        "未生成": "Not Generated",
        "已计算": "Calculated",
        "未计算": "Not Calculated",
        "已统计": "Counted",
        "未统计": "Not Counted",
        "已分析": "Analyzed",
        "未分析": "Not Analyzed",
        "已预测": "Predicted",
        "未预测": "Not Predicted",
        "已推荐": "Recommended",
        "未推荐": "Not Recommended",
        "已评价": "Rated",
        "未评价": "Not Rated",
        "已评论": "Commented",
        "未评论": "Not Commented",
        "已点赞": "Liked",
        "未点赞": "Not Liked",
        "已收藏": "Favorited",
        "未收藏": "Not Favorited",
        "已关注": "Followed",
        "未关注": "Not Followed",
        "已分享": "Shared",
        "未分享": "Not Shared",
        "已转发": "Forwarded",
        "未转发": "Not Forwarded",
        "已举报": "Reported",
        "未举报": "Not Reported",
        "已屏蔽": "Blocked",
        "未屏蔽": "Not Blocked",
        "已拉黑": "Blacklisted",
        "未拉黑": "Not Blacklisted",
        "已解封": "Unblocked",
        "未解封": "Not Unblocked",
        "已认证": "Authenticated",
        "未认证": "Not Authenticated",
        "已验证": "Verified",
        "未验证": "Not Verified",
        "已授权": "Authorized",
        "未授权": "Not Authorized",
        "已登录": "Logged In",
        "未登录": "Not Logged In",
        "已注册": "Registered",
        "未注册": "Unregistered",
        "已激活": "Activated",
        "未激活": "Not Activated",
        "已禁用": "Disabled",
        "未禁用": "Not Disabled",
        "已启用": "Enabled",
        "未启用": "Not Enabled",
        "已锁定": "Locked",
        "未锁定": "Not Locked",
        "已解锁": "Unlocked",
        "未解锁": "Not Unlocked",
        "已过期": "Expired",
        "未过期": "Not Expired",
        "已失效": "Invalid",
        "未失效": "Valid",
        "已生效": "Effective",
        "未生效": "Not Effective",
        "已开始": "Started",
        "未开始": "Not Started",
        "已结束": "Ended",
        "未结束": "Not Ended",
        "已完成": "Completed",
        "未完成": "Not Completed",
        "已取消": "Cancelled",
        "未取消": "Not Cancelled",
        "已暂停": "Paused",
        "未暂停": "Not Paused",
        "已继续": "Resumed",
        "未继续": "Not Resumed",
        "已停止": "Stopped",
        "未停止": "Not Stopped",
        "已重启": "Restarted",
        "未重启": "Not Restarted",
        "已关闭": "Closed",
        "未关闭": "Not Closed",
        "已打开": "Opened",
        "未打开": "Not Opened",
        "已显示": "Shown",
        "未显示": "Not Shown",
        "已隐藏": "Hidden",
        "未隐藏": "Not Hidden",
        "已排序": "Sorted",
        "未排序": "Not Sorted",
        "已分组": "Grouped",
        "未分组": "Not Grouped",
        "已筛选": "Filtered",
        "未筛选": "Not Filtered",
        "已搜索": "Searched",
        "未搜索": "Not Searched",
        "已刷新": "Refreshed",
        "未刷新": "Not Refreshed",
        "已加载": "Loaded",
        "未加载": "Not Loaded",
        "已保存": "Saved",
        "未保存": "Not Saved",
        "已提交": "Submitted",
        "未提交": "Not Submitted",
        "已确认": "Confirmed",
        "未确认": "Not Confirmed",
        "已发送": "Sent",
        "未发送": "Not Sent",
        "已接收": "Received",
        "未接收": "Not Received",
        "已读": "Read",
        "未读": "Unread",
        "已回复": "Replied",
        "未回复": "Not Replied",
        "已标记": "Marked",
        "未标记": "Unmarked",
        "已收藏": "Favorited",
        "未收藏": "Not Favorited",
        "已分享": "Shared",
        "未分享": "Not Shared",
        "已转发": "Forwarded",
        "未转发": "Not Forwarded",
        "已举报": "Reported",
        "未举报": "Not Reported",
        "已屏蔽": "Blocked",
        "未屏蔽": "Not Blocked",
        "已拉黑": "Blacklisted",
        "未拉黑": "Not Blacklisted",
        "已解封": "Unblocked",
        "未解封": "Not Unblocked",
        "已认证": "Authenticated",
        "未认证": "Not Authenticated",
        "已验证": "Verified",
        "未验证": "Not Verified",
        "已授权": "Authorized",
        "未授权": "Not Authorized",
        
        # Warehouse management terms
        "仓库": "Warehouse",
        "仓库区域": "Warehouse Area",
        "仓库货架": "Warehouse Shelf",
        "货架编码": "Shelf Code",
        "货架名称": "Shelf Name",
        "货架类型": "Shelf Type",
        "货架状态": "Shelf Status",
        "货架容量": "Shelf Capacity",
        "货架位置": "Shelf Position",
        "货架描述": "Shelf Description",
        "仓库管理员": "Warehouse Manager",
        "入库时间": "Storage Time",
        "出库时间": "Outbound Time",
        "库存数量": "Inventory Quantity",
        "库存预警": "Inventory Warning",
        "库存阈值": "Inventory Threshold",
        "物料编码": "Material Code",
        "物料名称": "Material Name",
        "物料类型": "Material Type",
        "物料规格": "Material Specification",
        "物料单位": "Material Unit",
        "供应商编码": "Supplier Code",
        "供应商名称": "Supplier Name",
        "采购订单": "Purchase Order",
        "采购时间": "Purchase Time",
        "采购数量": "Purchase Quantity",
        "采购单价": "Purchase Unit Price",
        "采购总价": "Purchase Total Price",
        "销售订单": "Sales Order",
        "销售时间": "Sales Time",
        "销售数量": "Sales Quantity",
        "销售单价": "Sales Unit Price",
        "销售总价": "Sales Total Price",
        "客户编码": "Customer Code",
        "客户名称": "Customer Name",
        "客户类型": "Customer Type",
        "客户等级": "Customer Level",
        "客户地址": "Customer Address",
        "客户电话": "Customer Phone",
        "客户邮箱": "Customer Email",
        "产品编码": "Product Code",
        "产品名称": "Product Name",
        "产品类型": "Product Type",
        "产品规格": "Product Specification",
        "产品单位": "Product Unit",
        "产品价格": "Product Price",
        "产品描述": "Product Description",
        "订单状态": "Order Status",
        "支付状态": "Payment Status",
        "发货状态": "Shipping Status",
        "收货状态": "Receiving Status",
        "退货状态": "Return Status",
        "退款状态": "Refund Status",
        "物流公司": "Logistics Company",
        "物流单号": "Logistics Tracking Number",
        "发货时间": "Shipping Time",
        "收货时间": "Receiving Time",
        "发货地址": "Shipping Address",
        "收货地址": "Receiving Address",
        "发货人": "Shipper",
        "收货人": "Receiver",
        "发货电话": "Shipper Phone",
        "收货电话": "Receiver Phone",
        "备注信息": "Remarks Information",
        "附件文件": "Attachment File",
        "附件名称": "Attachment Name",
        "附件类型": "Attachment Type",
        "附件大小": "Attachment Size",
        "上传时间": "Upload Time",
        "下载时间": "Download Time",
        "操作日志": "Operation Log",
        "操作类型": "Operation Type",
        "操作时间": "Operation Time",
        "操作人": "Operator",
        "操作内容": "Operation Content",
        "操作结果": "Operation Result",
        "系统配置": "System Configuration",
        "配置项": "Configuration Item",
        "配置值": "Configuration Value",
        "配置类型": "Configuration Type",
        "配置描述": "Configuration Description",
        "系统参数": "System Parameter",
        "参数编码": "Parameter Code",
        "参数名称": "Parameter Name",
        "参数值": "Parameter Value",
        "参数类型": "Parameter Type",
        "参数描述": "Parameter Description",
        "系统菜单": "System Menu",
        "菜单编码": "Menu Code",
        "菜单名称": "Menu Name",
        "菜单类型": "Menu Type",
        "菜单链接": "Menu Link",
        "菜单图标": "Menu Icon",
        "菜单排序": "Menu Order",
        "菜单状态": "Menu Status",
        "父级菜单": "Parent Menu",
        "子级菜单": "Child Menu",
        "菜单权限": "Menu Permission",
        "角色菜单": "Role Menu",
        "用户菜单": "User Menu",
        "系统角色": "System Role",
        "角色编码": "Role Code",
        "角色名称": "Role Name",
        "角色类型": "Role Type",
        "角色权限": "Role Permission",
        "角色状态": "Role Status",
        "用户角色": "User Role",
        "部门角色": "Department Role",
        "岗位角色": "Position Role",
        "系统用户": "System User",
        "用户编码": "User Code",
        "用户名": "Username",
        "用户密码": "User Password",
        "用户类型": "User Type",
        "用户状态": "User Status",
        "用户级别": "User Level",
        "用户部门": "User Department",
        "用户岗位": "User Position",
        "用户角色": "User Role",
        "用户权限": "User Permission",
        "登录时间": "Login Time",
        "登录IP": "Login IP",
        "登录地点": "Login Location",
        "登录设备": "Login Device",
        "会话ID": "Session ID",
        "会话状态": "Session Status",
        "会话超时": "Session Timeout",
        "系统日志": "System Log",
        "日志类型": "Log Type",
        "日志级别": "Log Level",
        "日志内容": "Log Content",
        "日志时间": "Log Time",
        "日志来源": "Log Source",
        "日志用户": "Log User",
        "错误日志": "Error Log",
        "操作日志": "Operation Log",
        "访问日志": "Access Log",
        "登录日志": "Login Log",
        "系统异常": "System Exception",
        "异常类型": "Exception Type",
        "异常信息": "Exception Information",
        "异常时间": "Exception Time",
        "异常来源": "Exception Source",
        "异常处理": "Exception Handling",
        "系统通知": "System Notification",
        "通知类型": "Notification Type",
        "通知标题": "Notification Title",
        "通知内容": "Notification Content",
        "通知时间": "Notification Time",
        "通知状态": "Notification Status",
        "通知对象": "Notification Target",
        "通知方式": "Notification Method",
        "邮件通知": "Email Notification",
        "短信通知": "SMS Notification",
        "系统消息": "System Message",
        "消息类型": "Message Type",
        "消息标题": "Message Title",
        "消息内容": "Message Content",
        "消息时间": "Message Time",
        "消息状态": "Message Status",
        "消息发送者": "Message Sender",
        "消息接收者": "Message Receiver",
        "系统公告": "System Announcement",
        "公告标题": "Announcement Title",
        "公告内容": "Announcement Content",
        "公告时间": "Announcement Time",
        "公告状态": "Announcement Status",
        "公告发布者": "Announcement Publisher",
        "公告类型": "Announcement Type",
        "系统报表": "System Report",
        "报表编码": "Report Code",
        "报表名称": "Report Name",
        "报表类型": "Report Type",
        "报表格式": "Report Format",
        "报表数据": "Report Data",
        "报表时间": "Report Time",
        "报表状态": "Report Status",
        "报表生成者": "Report Generator",
        "数据统计": "Data Statistics",
        "统计类型": "Statistics Type",
        "统计时间": "Statistics Time",
        "统计数据": "Statistics Data",
        "统计结果": "Statistics Result",
        "数据分析": "Data Analysis",
        "分析类型": "Analysis Type",
        "分析方法": "Analysis Method",
        "分析时间": "Analysis Time",
        "分析数据": "Analysis Data",
        "分析结果": "Analysis Result",
        "数据导出": "Data Export",
        "导出类型": "Export Type",
        "导出格式": "Export Format",
        "导出时间": "Export Time",
        "导出数据": "Export Data",
        "导出状态": "Export Status",
        "数据导入": "Data Import",
        "导入类型": "Import Type",
        "导入格式": "Import Format",
        "导入时间": "Import Time",
        "导入数据": "Import Data",
        "导入状态": "Import Status",
        "数据备份": "Data Backup",
        "备份类型": "Backup Type",
        "备份时间": "Backup Time",
        "备份数据": "Backup Data",
        "备份状态": "Backup Status",
        "数据恢复": "Data Recovery",
        "恢复类型": "Recovery Type",
        "恢复时间": "Recovery Time",
        "恢复数据": "Recovery Data",
        "恢复状态": "Recovery Status",
        "系统监控": "System Monitoring",
        "监控类型": "Monitoring Type",
        "监控对象": "Monitoring Target",
        "监控指标": "Monitoring Metrics",
        "监控时间": "Monitoring Time",
        "监控数据": "Monitoring Data",
        "监控状态": "Monitoring Status",
        "性能监控": "Performance Monitoring",
        "资源监控": "Resource Monitoring",
        "安全监控": "Security Monitoring",
        "系统维护": "System Maintenance",
        "维护类型": "Maintenance Type",
        "维护时间": "Maintenance Time",
        "维护内容": "Maintenance Content",
        "维护状态": "Maintenance Status",
        "系统升级": "System Upgrade",
        "升级类型": "Upgrade Type",
        "升级时间": "Upgrade Time",
        "升级内容": "Upgrade Content",
        "升级状态": "Upgrade Status",
        "版本信息": "Version Information",
        "版本号": "Version Number",
        "版本名称": "Version Name",
        "版本类型": "Version Type",
        "版本时间": "Version Time",
        "版本状态": "Version Status",
        "系统设置": "System Settings",
        "设置类型": "Settings Type",
        "设置项": "Settings Item",
        "设置值": "Settings Value",
        "设置时间": "Settings Time",
        "设置状态": "Settings Status",
        "用户设置": "User Settings",
        "系统权限": "System Permissions",
        "权限类型": "Permission Type",
        "权限对象": "Permission Target",
        "权限操作": "Permission Operation",
        "权限状态": "Permission Status",
        "角色权限": "Role Permissions",
        "用户权限": "User Permissions",
        "部门权限": "Department Permissions",
        "岗位权限": "Position Permissions",
        "菜单权限": "Menu Permissions",
        "数据权限": "Data Permissions",
        "操作权限": "Operation Permissions",
        "系统安全": "System Security",
        "安全策略": "Security Policy",
        "安全规则": "Security Rules",
        "安全级别": "Security Level",
        "安全状态": "Security Status",
        "访问控制": "Access Control",
        "身份认证": "Identity Authentication",
        "权限验证": "Permission Verification",
        "数据加密": "Data Encryption",
        "数据解密": "Data Decryption",
        "安全日志": "Security Log",
        "系统接口": "System Interface",
        "接口类型": "Interface Type",
        "接口名称": "Interface Name",
        "接口地址": "Interface Address",
        "接口参数": "Interface Parameters",
        "接口状态": "Interface Status",
        "接口调用": "Interface Call",
        "接口响应": "Interface Response",
        "接口文档": "Interface Documentation",
        "API接口": "API Interface",
        "REST接口": "REST Interface",
        "SOAP接口": "SOAP Interface",
        "接口测试": "Interface Testing",
        "接口监控": "Interface Monitoring",
        "系统缓存": "System Cache",
        "缓存类型": "Cache Type",
        "缓存键": "Cache Key",
        "缓存值": "Cache Value",
        "缓存时间": "Cache Time",
        "缓存状态": "Cache Status",
        "缓存清理": "Cache Cleanup",
        "系统队列": "System Queue",
        "队列类型": "Queue Type",
        "队列消息": "Queue Message",
        "队列状态": "Queue Status",
        "队列处理": "Queue Processing",
        "任务队列": "Task Queue",
        "消息队列": "Message Queue",
        "延迟队列": "Delay Queue",
        "优先队列": "Priority Queue",
        "系统调度": "System Scheduling",
        "调度类型": "Scheduling Type",
        "调度时间": "Scheduling Time",
        "调度任务": "Scheduled Task",
        "调度状态": "Scheduling Status",
        "定时任务": "Scheduled Task",
        "任务类型": "Task Type",
        "任务名称": "Task Name",
        "任务参数": "Task Parameters",
        "任务状态": "Task Status",
        "任务执行": "Task Execution",
        "任务结果": "Task Result",
        "系统工作流": "System Workflow",
        "工作流类型": "Workflow Type",
        "工作流名称": "Workflow Name",
        "工作流状态": "Workflow Status",
        "工作流步骤": "Workflow Steps",
        "流程定义": "Process Definition",
        "流程实例": "Process Instance",
        "流程状态": "Process Status",
        "流程变量": "Process Variables",
        "流程历史": "Process History",
        "审批流程": "Approval Process",
        "审批状态": "Approval Status",
        "审批节点": "Approval Node",
        "审批人": "Approver",
        "审批时间": "Approval Time",
        "审批意见": "Approval Comments",
        "系统表单": "System Form",
        "表单类型": "Form Type",
        "表单名称": "Form Name",
        "表单字段": "Form Fields",
        "表单数据": "Form Data",
        "表单状态": "Form Status",
        "表单验证": "Form Validation",
        "表单提交": "Form Submission",
        "动态表单": "Dynamic Form",
        "表单设计": "Form Design",
        "表单模板": "Form Template",
        "系统字典": "System Dictionary",
        "字典类型": "Dictionary Type",
        "字典编码": "Dictionary Code",
        "字典名称": "Dictionary Name",
        "字典项": "Dictionary Items",
        "字典值": "Dictionary Value",
        "字典状态": "Dictionary Status",
        "数据字典": "Data Dictionary",
        "业务字典": "Business Dictionary",
        "系统代码": "System Code",
        "代码类型": "Code Type",
        "代码名称": "Code Name",
        "代码内容": "Code Content",
        "代码版本": "Code Version",
        "代码状态": "Code Status",
        "系统文件": "System Files",
        "文件类型": "File Type",
        "文件名称": "File Name",
        "文件路径": "File Path",
        "文件大小": "File Size",
        "文件时间": "File Time",
        "文件状态": "File Status",
        "文件上传": "File Upload",
        "文件下载": "File Download",
        "文件预览": "File Preview",
        "文件编辑": "File Editing",
        "文件删除": "File Deletion",
        "系统图片": "System Images",
        "图片类型": "Image Type",
        "图片名称": "Image Name",
        "图片路径": "Image Path",
        "图片大小": "Image Size",
        "图片时间": "Image Time",
        "图片状态": "Image Status",
        "图片上传": "Image Upload",
        "图片下载": "Image Download",
        "图片预览": "Image Preview",
        "图片编辑": "Image Editing",
        "图片删除": "Image Deletion",
        "系统文档": "System Documents",
        "文档类型": "Document Type",
        "文档名称": "Document Name",
        "文档路径": "Document Path",
        "文档大小": "Document Size",
        "文档时间": "Document Time",
        "文档状态": "Document Status",
        "文档上传": "Document Upload",
        "文档下载": "Document Download",
        "文档预览": "Document Preview",
        "文档编辑": "Document Editing",
        "文档删除": "Document Deletion",
        "系统视频": "System Videos",
        "视频类型": "Video Type",
        "视频名称": "Video Name",
        "视频路径": "Video Path",
        "视频大小": "Video Size",
        "视频时间": "Video Time",
        "视频状态": "Video Status",
        "视频上传": "Video Upload",
        "视频下载": "Video Download",
        "视频预览": "Video Preview",
        "视频编辑": "Video Editing",
        "视频删除": "Video Deletion",
        "系统音频": "System Audio",
        "音频类型": "Audio Type",
        "音频名称": "Audio Name",
        "音频路径": "Audio Path",
        "音频大小": "Audio Size",
        "音频时间": "Audio Time",
        "音频状态": "Audio Status",
        "音频上传": "Audio Upload",
        "音频下载": "Audio Download",
        "音频预览": "Audio Preview",
        "音频编辑": "Audio Editing",
        "音频删除": "Audio Deletion"
    }
    
    # Read complete SQL file (to continue translation)
    with open("jeecg-boot/db/jeecgboot-mysql-5.7_complete.sql", 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Apply translations
    translated_content = content
    translation_count = 0
    duplicate_count = 0
    
    # Check for duplicates in translations
    chinese_values = list(translations.values())
    duplicates = []
    for i, value in enumerate(chinese_values):
        if chinese_values.count(value) > 1:
            duplicates.append(value)
            duplicate_count += 1
    
    if duplicates:
        print(f"Found {duplicate_count} duplicate translations:")
        for dup in duplicates:
            print(f"  - '{dup}'")
    
    # Apply translations
    for chinese, english in translations.items():
        if chinese in translated_content:
            translated_content = translated_content.replace(chinese, english)
            translation_count += 1
            print(f"Translated: '{chinese}' -> '{english}'")
    
    # Write translated SQL file
    with open("jeecg-boot/db/jeecgboot-mysql-5.7_final_translated.sql", 'w', encoding='utf-8') as f:
        f.write(translated_content)
    
    print(f"\nTranslation finished! Applied {translation_count} translations.")
    
    # Check for any remaining Chinese text
    chinese_pattern = re.compile(r'[\u4e00-\u9fff]+')
    remaining_chinese = chinese_pattern.findall(translated_content)
    
    if remaining_chinese:
        print(f"\nWarning: {len(set(remaining_chinese))} unique Chinese text strings still remain:")
        for text in sorted(set(remaining_chinese)):
            print(f"  - {text}")
    else:
        print("\nSuccess! All Chinese text has been translated.")

if __name__ == "__main__":
    translate_and_check_duplicates()