CREATE TABLE `sys_log0` (
  `id` varchar(32) NOT NULL,
  `log_type` int(2) DEFAULT NULL COMMENT 'Log type（1Login log，2Operation log）',
  `log_content` varchar(1000) DEFAULT NULL COMMENT 'Log content',
  `operate_type` int(2) DEFAULT NULL COMMENT 'Operation type',
  `userid` varchar(32) DEFAULT NULL COMMENT 'Manage user account',
  `username` varchar(100) DEFAULT NULL COMMENT 'Operation user name',
  `ip` varchar(100) DEFAULT NULL COMMENT 'IP',
  `method` varchar(500) DEFAULT NULL COMMENT 'askjavamethod',
  `request_url` varchar(255) DEFAULT NULL COMMENT 'ask路径',
  `request_param` longtext DEFAULT NULL COMMENT 'ask参数',
  `request_type` varchar(10) DEFAULT NULL COMMENT 'ask类型',
  `cost_time` bigint(20) DEFAULT NULL COMMENT 'time consuming',
  `create_by` varchar(32) DEFAULT NULL COMMENT 'Creator',
  `create_time` datetime DEFAULT NULL COMMENT 'creation time',
  `update_by` varchar(32) DEFAULT NULL COMMENT 'Updater',
  `update_time` datetime DEFAULT NULL COMMENT 'Update time',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `index_table_userid` (`userid`) USING BTREE,
  KEY `index_logt_ype` (`log_type`) USING BTREE,
  KEY `index_operate_type` (`operate_type`) USING BTREE,
  KEY `index_createtime` (`create_time`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='System log table';

CREATE TABLE `sys_log1` (
  `id` varchar(32) NOT NULL,
  `log_type` int(2) DEFAULT NULL COMMENT 'Log type（1Login log，2Operation log）',
  `log_content` varchar(1000) DEFAULT NULL COMMENT 'Log content',
  `operate_type` int(2) DEFAULT NULL COMMENT 'Operation type',
  `userid` varchar(32) DEFAULT NULL COMMENT 'Manage user account',
  `username` varchar(100) DEFAULT NULL COMMENT 'Operation user name',
  `ip` varchar(100) DEFAULT NULL COMMENT 'IP',
  `method` varchar(500) DEFAULT NULL COMMENT 'askjavamethod',
  `request_url` varchar(255) DEFAULT NULL COMMENT 'ask路径',
  `request_param` longtext DEFAULT NULL COMMENT 'ask参数',
  `request_type` varchar(10) DEFAULT NULL COMMENT 'ask类型',
  `cost_time` bigint(20) DEFAULT NULL COMMENT 'time consuming',
  `create_by` varchar(32) DEFAULT NULL COMMENT 'Creator',
  `create_time` datetime DEFAULT NULL COMMENT 'creation time',
  `update_by` varchar(32) DEFAULT NULL COMMENT 'Updater',
  `update_time` datetime DEFAULT NULL COMMENT 'Update time',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `index_table_userid` (`userid`) USING BTREE,
  KEY `index_logt_ype` (`log_type`) USING BTREE,
  KEY `index_operate_type` (`operate_type`) USING BTREE,
  KEY `index_createtime` (`create_time`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='System log table';
