#
# XXL-JOB v2.4.0
# Copyright (c) 2015-present, xuxueli.

CREATE database if NOT EXISTS `xxl_job` default character set utf8mb4 collate utf8mb4_general_ci;
use `xxl_job`;

/*
 Navicat Premium Data Transfer

 Source Server         : mysql5.7
 Source Server Type    : MySQL
 Source Server Version : 50738 (5.7.38)
 Source Host           : 127.0.0.1:3306
 Source Schema         : xxl_job

 Target Server Type    : MySQL
 Target Server Version : 50738 (5.7.38)
 File Encoding         : 65001

 Date: 10/02/2025 13:49:31
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for xxl_job_group
-- ----------------------------
DROP TABLE IF EXISTS `xxl_job_group`;
CREATE TABLE `xxl_job_group`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `app_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'actuatorAppName',
  `title` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'actuatorname',
  `address_type` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'actuatoraddresstype：0=Automatic registration、1=Manual entry',
  `address_list` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'actuatoraddress list，Multiple addresses separated by commas',
  `update_time` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of xxl_job_group
-- ----------------------------
INSERT INTO `xxl_job_group` VALUES (1, 'xxl-job-executor-sample', 'Exampleactuator', 0, NULL, '2025-02-10 13:49:04');
INSERT INTO `xxl_job_group` VALUES (2, 'jeecg-demo', 'testDemomodule', 0, NULL, '2025-02-10 13:49:04');
INSERT INTO `xxl_job_group` VALUES (3, 'jeecg-system', 'systemSystemmodule', 0, NULL, '2025-02-10 13:49:04');

-- ----------------------------
-- Table structure for xxl_job_info
-- ----------------------------
DROP TABLE IF EXISTS `xxl_job_info`;
CREATE TABLE `xxl_job_info`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_group` int(11) NOT NULL COMMENT 'actuatorprimary keyID',
  `job_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `add_time` datetime NULL DEFAULT NULL,
  `update_time` datetime NULL DEFAULT NULL,
  `author` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'author',
  `alarm_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Alarm email',
  `schedule_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'NONE' COMMENT 'Scheduling type',
  `schedule_conf` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Scheduling configuration，The value meaning depends onScheduling type',
  `misfire_strategy` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'DO_NOTHING' COMMENT 'Scheduling Expiration Policy',
  `executor_route_strategy` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'actuatorRouting strategy',
  `executor_handler` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'actuatorTaskhandler',
  `executor_param` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'actuatorTaskparameter',
  `executor_block_strategy` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Blocking handling strategy',
  `executor_timeout` int(11) NOT NULL DEFAULT 0 COMMENT 'Task execution timeout，Unit second',
  `executor_fail_retry_count` int(11) NOT NULL DEFAULT 0 COMMENT 'Number of failed retries',
  `glue_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'GLUEtype',
  `glue_source` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'GLUEsource code',
  `glue_remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'GLUERemark',
  `glue_updatetime` datetime NULL DEFAULT NULL COMMENT 'GLUEUpdate time',
  `child_jobid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'subtaskID，Multiple commas separated',
  `trigger_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'Scheduling status：0-stop，1-run',
  `trigger_last_time` bigint(13) NOT NULL DEFAULT 0 COMMENT 'Last scheduled time',
  `trigger_next_time` bigint(13) NOT NULL DEFAULT 0 COMMENT 'Next scheduling time',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of xxl_job_info
-- ----------------------------
INSERT INTO `xxl_job_info` VALUES (1, 1, 'testTask1', '2018-11-03 22:21:31', '2024-08-21 22:30:30', 'XXL', '', 'CRON', '0 0 0 * * ? *', 'DO_NOTHING', 'FIRST', 'demoJob', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUECode initialization', '2018-11-03 22:21:31', '', 1, 1729353600000, 1739203200000);
INSERT INTO `xxl_job_info` VALUES (2, 3, 'testjeecg xxljob', '2024-08-21 22:41:10', '2024-08-21 22:41:30', 'JEECG', '', 'CRON', '* * * * * ?', 'DO_NOTHING', 'FIRST', 'demoJob', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUECode initialization', '2024-08-21 22:41:10', '', 1, 1739166572000, 1739166573000);

-- ----------------------------
-- Table structure for xxl_job_lock
-- ----------------------------
DROP TABLE IF EXISTS `xxl_job_lock`;
CREATE TABLE `xxl_job_lock`  (
  `lock_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'lock name',
  PRIMARY KEY (`lock_name`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of xxl_job_lock
-- ----------------------------
INSERT INTO `xxl_job_lock` VALUES ('schedule_lock');

-- ----------------------------
-- Table structure for xxl_job_log
-- ----------------------------
DROP TABLE IF EXISTS `xxl_job_log`;
CREATE TABLE `xxl_job_log`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `job_group` int(11) NOT NULL COMMENT 'actuatorprimary keyID',
  `job_id` int(11) NOT NULL COMMENT 'Task，primary keyID',
  `executor_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'actuatoraddress，The address of this execution',
  `executor_handler` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'actuatorTaskhandler',
  `executor_param` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'actuatorTaskparameter',
  `executor_sharding_param` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'actuatorTask分片parameter，The format is like 1/2',
  `executor_fail_retry_count` int(11) NOT NULL DEFAULT 0 COMMENT 'Number of failed retries',
  `trigger_time` datetime NULL DEFAULT NULL COMMENT 'Scheduling-time',
  `trigger_code` int(11) NOT NULL COMMENT 'Scheduling-result',
  `trigger_msg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'Scheduling-log',
  `handle_time` datetime NULL DEFAULT NULL COMMENT 'implement-time',
  `handle_code` int(11) NOT NULL COMMENT 'implement-state',
  `handle_msg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'implement-log',
  `alarm_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'Alarmstate：0-default、1-No need to warn、2-Alarm successful、3-Alarm failed',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `I_trigger_time`(`trigger_time`) USING BTREE,
  INDEX `I_handle_code`(`handle_code`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6761 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of xxl_job_log
-- ----------------------------
INSERT INTO `xxl_job_log` VALUES (6618, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:09', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6619, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:10', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6620, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:11', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6621, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:12', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6622, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:13', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6623, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:14', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6624, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:15', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6625, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:16', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6626, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:17', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6627, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:18', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6628, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:19', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6629, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:20', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6630, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:21', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6631, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:22', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6632, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:23', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6633, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:24', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6634, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:25', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6635, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:26', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6636, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:27', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6637, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:28', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6638, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:29', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6639, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:30', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6640, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:31', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6641, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:32', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6642, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:33', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6643, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:34', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6644, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:35', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6645, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:36', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6646, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:37', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6647, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:38', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6648, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:39', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6649, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:40', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6650, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:41', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6651, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:42', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6652, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:43', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6653, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:44', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6654, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:45', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6655, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:46', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6656, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:47', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6657, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:48', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6658, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:49', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6659, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:50', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6660, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:51', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6661, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:52', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6662, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:53', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6663, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:54', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6664, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:55', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6665, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:56', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6666, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:57', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6667, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:58', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6668, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:59', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6669, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:00', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6670, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:01', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6671, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:02', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6672, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:03', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6673, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:04', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6674, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:05', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6675, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:06', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6676, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:07', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6677, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:08', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6678, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:09', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6679, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:10', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6680, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:11', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6681, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:12', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6682, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:13', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6683, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:14', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6684, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:15', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6685, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:16', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6686, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:17', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6687, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:18', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6688, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:19', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6689, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:20', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6690, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:21', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6691, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:22', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6692, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:23', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6693, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:24', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6694, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:25', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6695, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:26', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6696, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:27', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6697, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:28', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6698, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:29', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6699, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:30', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6700, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:31', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6701, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:32', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6702, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:33', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6703, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:34', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6704, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:35', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6705, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:36', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6706, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:37', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6707, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:38', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6708, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:39', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6709, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:40', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6710, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:41', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6711, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:42', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6712, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:43', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6713, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:44', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6714, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:45', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6715, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:46', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6716, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:47', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6717, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:48', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6718, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:49', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6719, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:50', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6720, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:51', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6721, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:52', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6722, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:53', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6723, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:54', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6724, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:55', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6725, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:56', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6726, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:57', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6727, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:58', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6728, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:59', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6729, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:00', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6730, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:01', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6731, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:02', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6732, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:03', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6733, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:04', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6734, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:05', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6735, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:06', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6736, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:07', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6737, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:08', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6738, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:09', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6739, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:10', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6740, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:11', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6741, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:12', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6742, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:13', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6743, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:14', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6744, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:15', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6745, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:16', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6746, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:17', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6747, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:18', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6748, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:19', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6749, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:20', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6750, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:21', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6751, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:22', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6752, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:23', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6753, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:24', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 2);
INSERT INTO `xxl_job_log` VALUES (6754, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:25', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 0);
INSERT INTO `xxl_job_log` VALUES (6755, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:26', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 0);
INSERT INTO `xxl_job_log` VALUES (6756, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:27', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 0);
INSERT INTO `xxl_job_log` VALUES (6757, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:28', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 0);
INSERT INTO `xxl_job_log` VALUES (6758, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:29', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 0);
INSERT INTO `xxl_job_log` VALUES (6759, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:30', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 0);
INSERT INTO `xxl_job_log` VALUES (6760, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:31', 500, 'Tasktriggertype：Crontrigger<br>Schedulingmachine：192.168.1.11<br>actuator-Registration method：Automatic registration<br>actuator-address list：null<br>Routing strategy：first one<br>Blocking handling strategy：Stand-alone serial<br>Tasktime outtime：0<br>Number of failed retries：0<br><br><span style=\"color:#00c0ef;\" > >>>>>>>>>>>triggerScheduling<<<<<<<<<<< </span><br>Schedulingfail：actuatoraddress为空<br><br>', NULL, 0, NULL, 0);

-- ----------------------------
-- Table structure for xxl_job_log_report
-- ----------------------------
DROP TABLE IF EXISTS `xxl_job_log_report`;
CREATE TABLE `xxl_job_log_report`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `trigger_day` datetime NULL DEFAULT NULL COMMENT 'Scheduling-time',
  `running_count` int(11) NOT NULL DEFAULT 0 COMMENT 'runmiddle-logquantity',
  `suc_count` int(11) NOT NULL DEFAULT 0 COMMENT 'implementsuccess-logquantity',
  `fail_count` int(11) NOT NULL DEFAULT 0 COMMENT 'implementfail-logquantity',
  `update_time` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `i_trigger_day`(`trigger_day`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 13 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of xxl_job_log_report
-- ----------------------------
INSERT INTO `xxl_job_log_report` VALUES (1, '2024-08-21 00:00:00', 70, 0, 5, NULL);
INSERT INTO `xxl_job_log_report` VALUES (2, '2024-08-20 00:00:00', 0, 0, 0, NULL);
INSERT INTO `xxl_job_log_report` VALUES (3, '2024-08-19 00:00:00', 0, 0, 0, NULL);
INSERT INTO `xxl_job_log_report` VALUES (4, '2024-09-10 00:00:00', 0, 0, 56, NULL);
INSERT INTO `xxl_job_log_report` VALUES (5, '2024-09-09 00:00:00', 0, 0, 0, NULL);
INSERT INTO `xxl_job_log_report` VALUES (6, '2024-09-08 00:00:00', 0, 0, 0, NULL);
INSERT INTO `xxl_job_log_report` VALUES (7, '2024-10-19 00:00:00', 0, 0, 6391, NULL);
INSERT INTO `xxl_job_log_report` VALUES (8, '2024-10-18 00:00:00', 0, 0, 0, NULL);
INSERT INTO `xxl_job_log_report` VALUES (9, '2024-10-17 00:00:00', 0, 0, 0, NULL);
INSERT INTO `xxl_job_log_report` VALUES (10, '2025-02-10 00:00:00', 0, 0, 116, NULL);
INSERT INTO `xxl_job_log_report` VALUES (11, '2025-02-09 00:00:00', 0, 0, 0, NULL);
INSERT INTO `xxl_job_log_report` VALUES (12, '2025-02-08 00:00:00', 0, 0, 0, NULL);

-- ----------------------------
-- Table structure for xxl_job_logglue
-- ----------------------------
DROP TABLE IF EXISTS `xxl_job_logglue`;
CREATE TABLE `xxl_job_logglue`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` int(11) NOT NULL COMMENT 'Task，primary keyID',
  `glue_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'GLUEtype',
  `glue_source` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'GLUEsource code',
  `glue_remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'GLUERemark',
  `add_time` datetime NULL DEFAULT NULL,
  `update_time` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of xxl_job_logglue
-- ----------------------------

-- ----------------------------
-- Table structure for xxl_job_registry
-- ----------------------------
DROP TABLE IF EXISTS `xxl_job_registry`;
CREATE TABLE `xxl_job_registry`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `registry_group` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `registry_key` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `registry_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `update_time` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `i_g_k_v`(`registry_group`, `registry_key`, `registry_value`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of xxl_job_registry
-- ----------------------------

-- ----------------------------
-- Table structure for xxl_job_user
-- ----------------------------
DROP TABLE IF EXISTS `xxl_job_user`;
CREATE TABLE `xxl_job_user`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'account',
  `password` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'password',
  `role` tinyint(4) NOT NULL COMMENT 'Role：0-Ordinary user、1-administrator',
  `permission` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'Permissions：actuatorIDlist，Multiple commas separated',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `i_username`(`username`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of xxl_job_user
-- ----------------------------
INSERT INTO `xxl_job_user` VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL);

SET FOREIGN_KEY_CHECKS = 1;

